baseurl = "https://qiangua.me"
languageCode = "en-us"
title = "采采流水"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "Books"
    url = "/books/"
    weight = 4
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 5
[[menu.main]]
    name = "Fragments"
    url = "/fragments/"
    weight = 6
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = " An Essay Concerning Human Understanding"
    footer = "&copy; [Qiangua](https://qiangua.me) 2019 | [Instagram](https://www.instagram.com/mlyqdd/)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex","python","lisp"]
  highlightjsTheme = "github"
